definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -44
    menu_name: main
    parent: ''
    expanded: false
    enabled: false
  user__page:
    weight: -49
    menu_name: account
    parent: ''
    expanded: false
    enabled: false
  apigee_edge__my_apps:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -30
  test_restapi__my_apps:
    weight: -48
    menu_name: main
    parent: ''
    enabled: true
    expanded: false
  apigee_edge__apps:
    weight: -50
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
  user__logout:
    weight: -48
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
