favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://open-banking.local/themes/custom/open_banking_portal_revised/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  open_banking_portal_revised: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
fluid_container: 1
table_responsive: '-1'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content_header: ''
  content: ''
  content_footer: ''
  sidebar_first: ''
  sidebar_second: ''
  footer: ''
table: ''
