<?php

/**
 * @file
 * Contains military_bank.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
/**
 * Implements hook_help().
 */
function military_bank_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the military_bank module.
    case 'help.page.military_bank':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Mb Customizations for vietnamese language') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_entity_base_field_info_alter().
 */
function military_bank_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
    /** @var \Drupal\Core\Field\FieldDefinitionInterface[] $fields */
    if ($entity_type->id() === 'user') {
        $fields['first_name']->setLabel(t('Họ'));
        $fields['last_name']->setLabel(t('Tên'));
    }
}


/**
 * Implements hook_menu_links_discovered_alter().
 */
function military_bank_menu_links_discovered_alter(&$links) {
    $links['user.logout']['class'] = 'Drupal\military_bank\Plugin\Menu\MyLoginLogoutMenuLink';
}